---

- name: ZOOKEEPER | Installing dependencies
  apt:
    pkg: "zookeeper"
    state: absent

- name: ZOOKEEPER | Installing dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ zookeeper_required_libs }}"
  tags:
    skip_ansible_lint

- name: ZOOKEEPER | Ensure zookeeper group
  group:
    name: "{{ zookeeper_group }}"

- name: ZOOKEEPER | Ensure zookeeper user
  user:
    name: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    home: /bin/false
  ignore_errors: true

- name: ZOOKEEPER | Create install path
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  with_items:
    - "{{ zookeeper_install_path }}"
    - "{{ zookeeper_conf_dir }}"
    - "{{ zookeeper_data_dir }}"
    - "{{ zookeeper_log_dir }}"

- name: ZOOKEEPER | Check zookeeper version
  command: echo status | nc localhost 2181
  register: zookeeper_check
  changed_when: false
  ignore_errors: true

- name: ZOOKEEPER | Untar zookeeper
  unarchive:
    extra_opts: ['--strip-components=1']
    src: "{{ zookeeper_url }}"
    remote_src: yes
    dest: "{{ zookeeper_install_path }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  when: zookeeper_force_reinstall or zookeeper_check|failed or zookeeper_version not in zookeeper_check.stdout


- name: ZOOKEEPER | Create systemd service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
  notify:
    - Restart zookeeper

- name: ZOOKEEPER | Remove upstart service
  file:
    path: /etc/init.d/zookeeper
    state: absent
