---

- include: Debian.yml
  when: ansible_os_family == 'Debian' and zookeeper_debian_apt_install

- include: Debian-tarball.yml
  when: ansible_os_family == 'Debian' and not zookeeper_debian_apt_install

- include: common-config.yml
