---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint

platforms:
  - name: zookeeper1
    groups:
      - zookeeper
    image: idealista/java-debian-ansible
    image_version: 3.1.1-debian9
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    networks:
      - name: zookeeper-network
        links:
          - zookeeper2:zookeeper2
          - zookeeper3:zookeeper3
    command: '/lib/systemd/systemd'

  - name: zookeeper2
    groups:
      - zookeeper
    image: idealista/java-debian-ansible
    image_version: 3.1.1-debian9
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    networks:
      - name: zookeeper-network
        links:
          - zookeeper1:zookeeper1
          - zookeeper3:zookeeper3
    command: '/lib/systemd/systemd'

  - name: zookeeper3
    groups:
      - zookeeper
    image: idealista/java-debian-ansible
    image_version: 3.1.1-debian9
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    networks:
      - name: zookeeper-network
        links:
          - zookeeper1:zookeeper1
          - zookeeper2:zookeeper2
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
